name: Release
on:
  # push:
    # tags: ['v*']
  workflow_dispatch:
jobs:
  build-pip:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-in-project: true
          installer-parallel: true

      - name: Build pip wheels
        run: |
          source $VENV
          poetry install
          poetry build -n
      
      - name: Upload built wheels
        uses: actions/upload-artifact@v3
        with:
          name: vanilla-installer_python-dist
          path: dist/*